### ISSUE TITLE
训练集

### ISSUE THREAD

**Issue by sunny0315** [minivision-ai/photo2cartoon#1]
请问提供的模型训练集中只有女性的数据吗？输入男性的图片生成的图片都被女性化了

**Comment by hao-qiang** [comment]
我们目前仅开源亚洲女性卡通画数据，开源模型也是基于这批数据训练的，您可以在小程序中体验各性别、年龄段的卡通化效果。

**Comment by lyastro** [comment]
可以提供trainA和testA部分的数据吗？

**Comment by hao-qiang** [comment]
domain A 数据暂不开放，您可以使用其他开源人脸数据集（如CelebA），我们提供了数据预处理脚本，您可按说明使用。

**Comment by lyastro** [comment]
明白了 谢谢

**Comment by ironyoung** [comment]
能问一下，你们的 trainB 和 testB，是找设计师手画的么？

**Comment by hao-qiang** [comment]
> 能问一下，你们的 trainB 和 testB，是找设计师手画的么？

开源的卡通画数据收集自互联网，我们另外找画师绘制了一批卡通数据用于训练小程序中的卡通化模型。
