### ISSUE TITLE
如何选取效果最好的模型 和 训练数据？

### ISSUE THREAD

**Issue by yuanxing-syy** [minivision-ai/photo2cartoon#13]
1.请问在README.md,您说"首先训练模型20万步，然后使用FID指标挑选出最优模型，最终挑选出的模型为迭代9万步时的模型。"
为什么要这样做而不是直接训练到代码里默认的100万步？以及如何用FID指标挑选呢？

2.请问小程序中演示的效果，您在训练时，真实照片和卡通画像各大约多少张呢？

3.之前看抖音的宝宝特效(比如把明星变成宝宝) 很火，就就很想尝试一下，请问用您的代码可以实现类似的效果吗？您对尝试这块，数据或代码上有什么建议吗？

恳请回复，万分感谢！

**Comment by hao-qiang** [comment]
感谢关注。
1. 训练时保存的一系列模型中的最佳模型并不一定是最后一次保存的模型，需要通过合适的评价指标去选择。我们使用图像生成领域的常用指标FID，该指标刻画了生成数据与目标数据的分布是否相近，由此根据FID去挑选生成效果最好的模型。关于FID的具体实现请参见相关论文或github项目。
2. 在训练小程序的模型时我们为每类人群各绘制了200张左右的卡通画，真人数据较容易获得，每类人群约1000张。
3. 由于我们希望生成的卡通画和真人照的辨识度尽可能相近，因此代码针对“ID不变”这一目标做了优化，可能不太适合做年龄编辑任务。我们使用原版的U-GAT-IT代码尝试过训练成人儿童转换和性别转换模型，AB域的数据各使用了约5000张，最终的效果从内容上看还是不错的，但是纹理上会有很多伪影，影响观感，稳定性较差。如果使用深度学习方法的话可以关注一下近期的人脸属性编辑相关论文。另外，还可以尝试借助人脸关键点使用Interactive Image Warping算法（类似于PS中的液化）来改变成人的脸型使之年轻化，这种方法鲁棒性会更好。

**Comment by yuanxing-syy** [comment]
感谢您的热心回复，谢谢！

**Comment by Z863058** [comment]
@hao-qiang，请问一下您所说的“每类人群”是指哪几类：“男性和女性”两类还是其他方式分成多类，谢谢！

**Comment by hao-qiang** [comment]
根据年龄和性别划分。

**Comment by Z863058** [comment]
@hao-qiang，感谢您的热心回复，谢谢！

**Comment by 0Colin** [comment]
> 2. 在训练小程序的模型时我们为每类人群各绘制了200张左右的卡通画，真人数据较容易获得，每类人群约1000张。

@hao-qiang 大佬您好，比较想了解一下这样划分比例的依据是什么呢？就譬如为什么现在B（卡通人脸）:A（真人）是大概1:5这样的比例呢？

**Comment by hao-qiang** [comment]
> @hao-qiang 大佬您好，比较想了解一下这样划分比例的依据是什么呢？就譬如为什么现在B（卡通人脸）:A（真人）是大概1:5这样的比例呢？

感谢提问！相比于卡通画，真人照场景更丰富，我们希望模型能够覆盖更多的输入场景，同时真人照比较容易获取，所以使用了远多于卡通画的真人照。但具体多少比例合适，我们没有做更多实验。
