### ISSUE TITLE
请问能分享下loss曲线或数据吗？

### ISSUE THREAD

**Issue by fantasy-fish** [minivision-ai/photo2cartoon#14]
您好，我现在训练的d_loss在1.0-2.0徘徊，g_loss在40-80徘徊，训练了8k左右个iteration。为了训练稳定，我把face_id loss的weight调成0了，其他权重保持默认值。想问下您的实验中最终的d_loss和g_loss长啥样吗？或者如果您有画loss曲线，能否分享下呢？感谢。

**Comment by hao-qiang** [comment]
在使用face_id loss时，最终训练收敛时的d_loss在1.5至2，g_loss在10至12，在8千步时的g_loss确实还比较高，您可以尝试训练10万步至收敛。

**Comment by fantasy-fish** [comment]
好的，感谢。我还有一个问题就是如果不做那些数据预处理的工作（比如说按照关键点旋转脸部以及背景置白），结果会差很多吗？

**Comment by hao-qiang** [comment]
当背景和头发或皮肤比较相近时，生成的卡通画背景容易渲染成头发或皮肤的纹理。

**Comment by fantasy-fish** [comment]
那如果不按照关键点旋转人脸呢？

**Comment by hao-qiang** [comment]
根据关键点校正人脸裁切，使人脸五官位置更统一，可以一定程度降低卡通化模型的训练难度。由于模型较为鲁棒，对于旋转的人脸，模型也能较好的生成卡通画。

**Comment by fantasy-fish** [comment]
好的，感谢
