### ISSUE TITLE
请教个问题，centos下跑出来的效果和win7上面不一样呢

### ISSUE THREAD

**Issue by shook2012** [minivision-ai/photo2cartoon#18]
centos下跑出来的效果和win7上面不一样，centos下跑出来的卡通图有些失真的感觉，但win7下跑出来示例的结果和你给出的效果就比较一致。centos下使用的是 nvida p4，win7使用的是Quadro K620，ps: 显卡驱动检查没问题

**Comment by hao-qiang** [comment]
测试过程分为：人脸检测、关键点检测、旋转校正裁剪人脸、人像分割、卡通化。
你可以先定位一下，差异出现在哪一步。

**Comment by shook2012** [comment]
或许是model传输时有问题。重新把你20200504的模型放进去之后，可以了。 多谢！
