### ISSUE TITLE
关于后端部署

### ISSUE THREAD

**Issue by xiuxiuxiaodi** [minivision-ai/photo2cartoon#2]
想问下你们小程序后端部署也是用的torch模型么 能简单说下部署小细节么 感谢

**Comment by hao-qiang** [comment]
卡通化子服务是基于pytorch模型部署的。

**Comment by xiuxiuxiaodi** [comment]
服务框架是什么呢  python的某个web框架？  还是新出的torchserve?

**Comment by hao-qiang** [comment]
python部署。
