### ISSUE TITLE
关于卡通画像的关键点检测问题

### ISSUE THREAD

**Issue by mrbulb** [minivision-ai/photo2cartoon#20]
您好，感谢您分享这个有趣的项目，我关于卡通画像关键点检测那边有一些疑问
现在的关键点检测大多都是在现实图像里面的，貌似不同直接套用在卡通画像里面，想问一下这边你们是怎么处理的，有用到迁移学习什么的吗？还是自己标注数据呢？

**Comment by hao-qiang** [comment]
由于卡通风格较为写实，我们自研的关键点检测器可以在写实卡通画上有较好的泛化性。因此在处理卡通数据时直接使用真人的关键点检测器，再人工筛查一下。

**Comment by mrbulb** [comment]
> 由于卡通风格较为写实，我们自研的关键点检测器可以在写实卡通画上有较好的泛化性。因此在处理卡通数据时直接使用真人的关键点检测器，再人工筛查一下。

哦哦，好的感谢解答，因为我是想迁移到日漫风格的那种上面，真人关键点试了效果不是很好，也想问一下您知道有这方面的相关工作吗？

**Comment by hao-qiang** [comment]
1. 由于日漫风格与真人ID相差较大，不是我们主要的探索方向。
2. 基于Unpaired Image Translation的日漫风格生成方法可以参考U-GAT-IT或最新的NICE-GAN。
3. 关于漫画关键点，你可以查阅漫画人脸检测器和关键点检测器相关论文。

**Comment by mrbulb** [comment]
> 1. 由于日漫风格与真人ID相差较大，不是我们主要的探索方向。
> 2. 基于Unpaired Image Translation的日漫风格生成方法可以参考U-GAT-IT或最新的NICE-GAN。
> 3. 关于漫画关键点，你可以查阅漫画人脸检测器和关键点检测器相关论文。

好的好的，感谢耐心的解答:smile:
