### ISSUE TITLE
有办法提高训练速度么？

### ISSUE THREAD

**Issue by qianlongzju** [minivision-ai/photo2cartoon#21]
每10个iteration大概耗时16s，200k iteration耗时有点长，

一般gan的batch_size很多设置为1， 有其他方法提升训练速度吗？

**Comment by hao-qiang** [comment]
使用预训练模型可以有效减少迭代步数。如果从头训练想提高GAN模型的收敛稳定性，可以参看相关的论文。

**Comment by qianlongzju** [comment]
多谢回复。我这边使用预训练模型来调优，fid有下降，实际结果对比发现出现了很多棕黑色的阴影，很影响二次元的形象的观感，这个有方法解决吗？ 还是训练还没有充分？

**Comment by hao-qiang** [comment]
你可以多测试一些样本，观察fail case容易发生在哪些情形，再做进一步分析。“棕黑色的阴影”的结果方便贴一下吗？

**Comment by qianlongzju** [comment]
图片可以看一下这个。 [https://imgchr.com/i/Ys3EtA](url)

这个模型训练时试了下设置batch_size，跑起来有问题

**Comment by xyxxmb** [comment]
> 多谢回复。我这边使用预训练模型来调优，fid有下降，实际结果对比发现出现了很多棕黑色的阴影，很影响二次元的形象的观感，这个有方法解决吗？ 还是训练还没有充分？

你好，我最近也在重新训练这个项目，有一些训练细节感觉可以优化，方便讨论一下吗？邮箱联系：echobingo@foxmail.com
