### ISSUE TITLE
关于训练数据问题

### ISSUE THREAD

**Issue by un-human** [minivision-ai/photo2cartoon#22]
你好，我想问下，trainA人脸照片和trainB动漫人脸， 两份数据是需要对应人吗(或者说 trainB里面都是trainA里人的动漫脸)？
比如  trainA 目录下的  a.jpg 和 trainB目录下的 a.jpg  是同一个人，因为我看你用了feature计算特征距离

**Comment by qianlongzju** [comment]
应该不需要，这里的方法是unpaired

**Comment by un-human** [comment]
> 应该不需要，这里的方法是unpaired

是的，不需要，我没认真看简介，不好意思
简介： ‘本任务的输入输出轮廓并非一一对应，例如卡通风格的眼睛更大、下巴更瘦；且成对的数据绘制难度大、成本较高，因此我们采用unpaired image translation方法来实现。’

多谢
