### ISSUE TITLE
关于训练数据

### ISSUE THREAD

**Issue by payne53** [minivision-ai/photo2cartoon#27]
您好，非常不错的工作。
由于开源模型基于女性数据训练，因此结果带有明显的女性特征，而小程序的结果泛化能力更强。在 Readme 中，提到内部训练数据是200多张定制化的卡通画，想请问一下，这200多张是包含了男、女总共的数据大小吗？

**Comment by bailiqun** [comment]
目前开源只用200张左右女性数据训练，小程序使用更多精细分类后的数据进行训练

**Comment by payne53** [comment]
方便请问一下，如果需要达到小程序中那样的效果，大概需要多少精细分类的数据吗

**Comment by hao-qiang** [comment]
我们对性别和年龄进行了分类，每类使用的卡通画约200张左右。

**Comment by payne53** [comment]
好的，谢谢！
