### ISSUE TITLE
这个有移动端的应用吗，能在移动端进行实时计算吗，不要上传到服务端的那种？

### ISSUE THREAD

**Issue by ZhangZoffy** [minivision-ai/photo2cartoon#28]

**Comment by hao-qiang** [comment]
由于从上传照片到生成卡通化中间会经过多个模型，无法保证在所有机型上都能流畅运行，同时考虑到生成效果，我们没有对模型进行压缩，所以没有直接做移动端的部署。

**Comment by ZhangZoffy** [comment]
后期会考虑移动端的吗？就像抖音的人脸卡通化那样。毕竟移动端的使用范围更广。

**Comment by ZhangZoffy** [comment]
> 由于从上传照片到生成卡通化中间会经过多个模型，无法保证在所有机型上都能流畅运行，同时考虑到生成效果，我们没有对模型进行压缩，所以没有直接做移动端的部署。
后期会考虑移动端的吗？就像抖音的人脸卡通化那样。毕竟移动端的使用范围更广。

**Comment by hao-qiang** [comment]
直接部署在移动端的卡通化方案大多是基于传统图像处理、贴图、3d模型，基于GAN的卡通化服务基本上都是部署在服务器上的。

**Comment by ZhangZoffy** [comment]
> 直接部署在移动端的卡通化方案大多是基于传统图像处理、贴图、3d模型，基于GAN的卡通化服务基本上都是部署在服务器上的。

受教了，非常感谢。项目确实很有趣~

**Comment by amazingyyc** [comment]
我刚上架了移动端的APP：https://apps.apple.com/cn/app/id1516638063
欢迎试用🤣🤣🤣

**Comment by YeHaijia** [comment]
> 我刚上架了移动端的APP：https://apps.apple.com/cn/app/id1516638063
> 欢迎试用🤣🤣🤣

有没有安卓端的呀？

**Comment by amazingyyc** [comment]
暂时没有🤣

**Comment by dragen1860** [comment]
@hao-qiang @amazingyyc 你们好，我体验了抖音的动漫特效，应该是移动端离线跑的，他们用的是啥方案，和你们的一样吗？谢谢

**Comment by amazingyyc** [comment]
> @hao-qiang @amazingyyc 你们好，我体验了抖音的动漫特效，应该是移动端离线跑的，他们用的是啥方案，和你们的一样吗？谢谢

看过效果没体验过盲目猜测一下：
抖音应该也是类似的方案，只不过网络结构应该很小且针对手机进行优化了。
观察抖音的效果无论拍摄者长什么样生成的漫画形象基本类似，猜测他的训练数据集做了限制，漫画形象只有一个或者少量接近的形象，这样用很小的网络结构就可以生成不错的效果，但是多样性确不好。

BTW：我用的原始的UGATIT模型，没作任何修改，在手机上运行很慢。
