### ISSUE TITLE
关于安装test

### ISSUE THREAD

**Issue by zhangyunming** [minivision-ai/photo2cartoon#3]
hi，你好，我在windows下进行安装测试，但是一直在：
Downloading the Face Alignment Network(FAN). Please wait...

然后下载中断，有什么其他的解决方式吗，比如我先下载这个FAN之类的

另外，你们小程序是输入512，然后训练的trainb部分也是只有200多张吗？

**Comment by hao-qiang** [comment]
1. 问题出在下载关键点检测模型FAN，本项目使用的是开源人脸检测和关键点检测库face-alignment，你可以在 https://github.com/1adrianb/face-alignment 项目了解更多，或使用其他检测模型。
2. 尽管训练小程序模型使用了更高的分辨率输入，但在训练每个人群种类时domain B训练数据也仅为200多张，并配合数据增广策略。

**Comment by Ricelll** [comment]
我也出现下载FAN中断这个问题，在网上搜到下载这个模型的方法。
https://www.cnblogs.com/cation/p/11144464.html

**Comment by zerollzeng** [comment]
If you press ctrl+c while downloading FAN, then you can easily find the download path via traceback. and the path was in face_align source code.
A simple solution for linux:
download path: https://www.adrianbulat.com/downloads/python-fan/2DFAN-4.pth.tar
and put it ~/.face_alignment/data/
