### ISSUE TITLE
为什么我用你们官方的预训练模型实现的效果很差？

### ISSUE THREAD

**Issue by wwzh2015** [minivision-ai/photo2cartoon#30]
和你们demo里的图片不一样？
https://s1.ax1x.com/2020/06/23/NUcwr9.png

**Comment by hao-qiang** [comment]
是否方便把原图发我一下测试，关于开源模型和小程序效果的差异请见readme。

**Comment by wwzh2015** [comment]
> 是否方便把原图发我一下测试，关于开源模型和小程序效果的差异请见readme。

原图在此：https://s1.ax1x.com/2020/06/24/NaL0xJ.jpg

我理解，但是你们既然走开源路线，应该发布个稍微能用的模型把，你们现在这个预训练模型出来的是个半成品呀，看不到效果。

**Comment by hao-qiang** [comment]
![cartoon_result](https://user-images.githubusercontent.com/28535732/85519330-e92f4d00-b633-11ea-8000-79d0ee5f93fd.png)

我测试了一下效果还是不错的，没有对图像进行任何处理，直接使用如下命令：

> python test.py --photo_path NaL0x.jpg --save_path result.png。

我们的代码和模型在5月4日进行了更新，但是你似乎使用的是更新后的代码和更新前的模型，请更新模型。

![image](https://user-images.githubusercontent.com/28535732/85520241-34962b00-b635-11ea-8d61-5df18cb1fc88.png)

**Comment by panxinmiao** [comment]
> > 是否方便把原图发我一下测试，关于开源模型和小程序效果的差异请见readme。
> 
> 原图在此：https://s1.ax1x.com/2020/06/24/NaL0xJ.jpg
> 
> 我理解，但是你们既然走开源路线，应该发布个稍微能用的模型把，你们现在这个预训练模型出来的是个半成品呀，看不到效果。

我觉得你搞错了，开源的是技术而不是业务。我们介绍了技术原理，开源了整个训练代码，你完全可以根据自己需求去定制使用我们开源的技术。提供预训练模型只是开源之外的额外内容。
并且，我们觉得这个预训练模型本身在特定人群上效果也很不错了。
推荐你在提问之前好好阅读一下《提问的智慧》。https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by wwzh2015** [comment]
> ![cartoon_result](https://user-images.githubusercontent.com/28535732/85519330-e92f4d00-b633-11ea-8000-79d0ee5f93fd.png)
> 
> 我测试了一下效果还是不错的，没有对图像进行任何处理，直接使用如下命令：
> 
> > python test.py --photo_path NaL0x.jpg --save_path result.png。
> 
> 我们的代码和模型在5月4日进行了更新，但是你似乎使用的是更新后的代码和更新前的模型，请更新模型。
> 
> ![image](https://user-images.githubusercontent.com/28535732/85520241-34962b00-b635-11ea-8d61-5df18cb1fc88.png)

非常感谢您，我已经实现了基本功能，现在就是转换后的脸有点发白，调哪个参数可以改善呢？

**Comment by hao-qiang** [comment]
> 非常感谢您，我已经实现了基本功能，现在就是转换后的脸有点发白，调哪个参数可以改善呢？

有两种方法：
- 将数据中的卡通画肤色调成想要的颜色，重新训练模型。
- 使用图像处理方法加滤镜。

**Comment by wwzh2015** [comment]
> > 非常感谢您，我已经实现了基本功能，现在就是转换后的脸有点发白，调哪个参数可以改善呢？
> 
> 有两种方法：
> 
> * 将数据中的卡通画肤色调成想要的颜色，重新训练模型。
> * 使用图像处理方法加滤镜。

感谢， 已经用后一种方法实现了。

**Comment by zhanglaplace** [comment]
> > > 非常感谢您，我已经实现了基本功能，现在就是转换后的脸有点发白，调哪个参数可以改善呢？
> > 
> > 
> > 有两种方法：
> > 
> > * 将数据中的卡通画肤色调成想要的颜色，重新训练模型。
> > * 使用图像处理方法加滤镜。
> 
> 感谢， 已经用后一种方法实现了。

我这边感觉也发白，能请教下这边滤镜怎么处理的吗
