### ISSUE TITLE
请问你是怎么成功把pytorch1.4和tensorflow1.14装到同一个环境里面的

### ISSUE THREAD

**Issue by tuobay** [minivision-ai/photo2cartoon#31]
按照你们的要求，请问你是怎么成功把pytorch1.4和tensorflow1.14装到同一个环境里面的，因为pytorch1.14需要cuda10.2，而tensorflow1.14需要cuda10.0，这个问题你们是怎么解决的？

**Comment by Decalogue** [comment]
不知道官方怎么做的,我是用的 pytorch1.2,1.2跑是完全可以的

**Comment by DWCTOD** [comment]
> 不知道官方怎么做的,我是用的 pytorch1.2,1.2跑是完全可以的

Downloading the Face Alignment Network(FAN). Please wait...
一直卡在这里不知道是怎么回事

**Comment by Decalogue** [comment]
@DWCTOD Face alignment 要下载模型的,保证网络通畅,耐心等待下载完成安装好

**Comment by hao-qiang** [comment]
1. 建议使用conda配置环境，pytorch1.0+，tensorflow1.12+应该都可以运行。如果只是测试的话装cpu版的也可以。
2. 关于关键点检测模型下载问题可以参考 #3

**Comment by DWCTOD** [comment]
太感谢了了，我参考 #3 确实可以了
