### ISSUE TITLE
运行demo一直提示: Downloading the Face Alignment Network(FAN). Please wait...

### ISSUE THREAD

**Issue by abo123456789** [minivision-ai/photo2cartoon#32]
运行:
 python test.py --photo_path ./images/photo_test.jpg --save_path ./images/cartoon_result.png

一直提示:
Downloading the Face Alignment Network(FAN). Please wait...

国内下载不动

有什么办法快速下载这个包吗？

**Comment by hao-qiang** [comment]
关于关键点检测模型下载问题可以参考 #3
