### ISSUE TITLE
finetuning

### ISSUE THREAD

**Issue by ghost** [minivision-ai/photo2cartoon#40]
how can I finetune the existing photo2cartoon weights, I loaded the weights but then the training starts from 0 iterations

**Comment by hao-qiang** [comment]
You can finetune with '--pretrained_weights', and step will start from 0.

**Comment by ghost** [comment]
@hao-qiang ok that is kind of confusing compared to the original ugatit when you load the weights training starts from the last epoch of the saved model, can there be some indication that it is starting from the previous checkpoint?

**Comment by hao-qiang** [comment]
Please refer to：
https://github.com/minivision-ai/photo2cartoon/blob/7590ed0396e648fb7437cd98a5cc59289d4ba5c1/models/UGATIT_sadalin_hourglass.py#L137-L146
You can change pretrained weights' name and get step from it.

**Comment by ghost** [comment]
@hao-qiang I tried that but training start at 0
<img width="831" alt="Screen Shot 2020-08-08 at 1 28 31 PM" src="https://user-images.githubusercontent.com/6818285/89716451-239e4080-d97b-11ea-9689-4ba73acf6a03.png">
