### ISSUE TITLE
使用test.py后，face alignment提示报错

### ISSUE THREAD

**Issue by shenghanqin** [minivision-ai/photo2cartoon#41]
我是Python新手，我在使用 test.py 时碰到了问题。一直卡在 `self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)`这一句上，我猜测的原因为pytorch的模型没加载好。

<img width="835" alt="粘贴的图形-2" src="https://user-images.githubusercontent.com/6348297/89476010-20a92180-d7bc-11ea-976e-09dc29ca1505.png">
<img width="829" alt="粘贴的图形-1" src="https://user-images.githubusercontent.com/6348297/89476016-24d53f00-d7bc-11ea-8b60-97e5eefe1f73.png">

**Comment by shenghanqin** [comment]
@hao-qiang 已确认安装了对应的版本
```
pip install torch==1.4.0 torchvision==0.5.0
```

**Comment by hao-qiang** [comment]
这个是face-alignment库下载模型不成功导致的，关于关键点检测模型下载问题可以参考 #3
