### ISSUE TITLE
mask分割出错

### ISSUE THREAD

**Issue by danielkaifeng** [minivision-ai/photo2cartoon#43]
在另一台机器能跑出正确结果，但今天在另一台配置的机器上跑发现mask出不来。
发现｀utils/face_seg.py｀里output_op run出来的值并不是0-1之前，最大值有1.5300853e+26，非常奇怪，经过sigmoid的值怎么会大于1?

版本应该是没错的：
Python 3.6.9
tensorflow-gpu                1.14.0
感谢提供下排查思路！

**Comment by kuangyl0212** [comment]
请问作者大大，这个问题是怎么解决的，我这边分割出来的mask是竖条纹，不是面部的形状
