### ISSUE TITLE
转onnx报错

### ISSUE THREAD

**Issue by ycdhqzhiai** [minivision-ai/photo2cartoon#46]
ONNX export failed on ATen operator var because torch.onnx.symbolic_opset9.var does not exist，有大佬遇见过吗

**Comment by hao-qiang** [comment]
似乎是计算方差的操作出了问题。

**Comment by hao-qiang** [comment]
opset9中不包括var算子，可将torch.var()修改为torch.std()**2。

**Comment by hao-qiang** [comment]
onnx模型已上传
