### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by Jensen-JQ** [minivision-ai/photo2cartoon#47]
你好，在readme的Q&A中，你们描述小程序中的效果是使用了200张定制卡通图训练，这个数据量是不是太小了，还是说这200张定制的卡通图只是用来最后微调的？
此外，你们定制卡通图的时候应该是参照真实人脸图像找专业人士绘制的吧，这样的话是不是等于有了成对的训练数据，你们用成对的数据进行有监督学习么，这样对最后的效果会不会有提升呢？

**Comment by hao-qiang** [comment]
直接使用200多张卡通化就可以达到不错的效果，在我们训练的时候，由于有不同人群的卡通数据，所有会先使用所有数据训练一个base版本再分类别finetune。
我们的训练数据虽然你是成对的，但由于卡通化和真人照有所差异不能达到pixel级别的成对，所有还是基于非成对数据方法做的。当然你提到的有监督学习思路我们做过相关实验，由于成对数据较少效果不如非成对训练。至于非成对训练方法加上成对数据训练分支指导，也是值得尝试的。

**Comment by pkjq11** [comment]
> 直接使用200多张卡通化就可以达到不错的效果，在我们训练的时候，由于有不同人群的卡通数据，所有会先使用所有数据训练一个base版本再分类别finetune。
> 我们的训练数据虽然你是成对的，但由于卡通化和真人照有所差异不能达到pixel级别的成对，所有还是基于非成对数据方法做的。当然你提到的有监督学习思路我们做过相关实验，由于成对数据较少效果不如非成对训练。至于非成对训练方法加上成对数据训练分支指导，也是值得尝试的。

感谢回复，

**Comment by Jensen-JQ** [comment]
> 直接使用200多张卡通化就可以达到不错的效果，在我们训练的时候，由于有不同人群的卡通数据，所有会先使用所有数据训练一个base版本再分类别finetune。
> 我们的训练数据虽然你是成对的，但由于卡通化和真人照有所差异不能达到pixel级别的成对，所有还是基于非成对数据方法做的。当然你提到的有监督学习思路我们做过相关实验，由于成对数据较少效果不如非成对训练。至于非成对训练方法加上成对数据训练分支指导，也是值得尝试的。

感谢回复以及开源的代码，我准备按照你们的思路跑跑看
