### ISSUE TITLE
迪丽热巴

### ISSUE THREAD

**Issue by dream-in-night** [minivision-ai/photo2cartoon#48]
![image](https://user-images.githubusercontent.com/17213331/97849615-c32a5f80-1d2d-11eb-850b-a515b050a6a0.png)
![image](https://user-images.githubusercontent.com/17213331/97849662-d2111200-1d2d-11eb-8d73-2f2cae5679af.png)
还有待改进的地方，不少。

**Comment by hao-qiang** [comment]
测试图片最好选用正脸头部完整的数据。
