### ISSUE TITLE
判别器相关

### ISSUE THREAD

**Issue by itomorrower08** [minivision-ai/photo2cartoon#49]
作者，您好，您的工作做的非常棒，给了我很多启发。我想请问设置两个分别在layer=5和layer=7的判别器的用意是什么呢？另外这个参数的设置是否有什么经验可循？

**Comment by hao-qiang** [comment]
这一部分请参见U-GAT-IT，我们沿用其方法。

**Comment by itomorrower08** [comment]
感谢。另外还想请问下生成的图片清晰度不够或者说是对比度不够明显，请问是数据集的原因，还是有其他tricks进行处理呢？尝试过图像锐化等方法，效果都不理想。

**Comment by hao-qiang** [comment]
我们开源的模型输出分辨率为256，想提高清晰度的话需要调整输入大小，重新训练。
卡通结果由卡通训练数据的风格决定。
