### ISSUE TITLE
关于test

### ISSUE THREAD

**Issue by xiaosuzhang** [minivision-ai/photo2cartoon#5]
在window10环境中调用test.py：
python test.py --photo_path ./images/photo_test.jpg --save_path ./images/cartoon_result.png
程序没有报错，也无法得出结果。

Warning: this detector is deprecated. Please use a different one, i.e.: S3FD.
WARNING:tensorflow:From E:\DL_with_coding\photo2cartoon\utils\face_seg.py:13: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.
ConfigProto instead.

WARNING:tensorflow:From E:\DL_with_coding\photo2cartoon\utils\face_seg.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Sess
ion instead.

2020-04-22 11:46:56.162121: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary w
as not compiled to use: AVX AVX2
2020-04-22 11:46:56.167602: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2020-04-22 11:46:57.083446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1060 with Max-Q Design major: 6 minor: 1 memoryClockRate(GHz): 1.3415
pciBusID: 0000:01:00.0
2020-04-22 11:46:57.090947: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, ski
p dlopen check.
2020-04-22 11:46:57.096467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-04-22 11:46:58.398108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge
matrix:
2020-04-22 11:46:58.403445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2020-04-22 11:46:58.406841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2020-04-22 11:46:58.410200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task
:0/device:GPU:0 with 4714 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 with Max-Q Design, pci bus id: 0000:01:00.0, compute
capability: 6.1)
WARNING:tensorflow:From E:\DL_with_coding\photo2cartoon\utils\face_seg.py:26: FastGFile.__init__ (from tensorflow.python.platform.gfile) is d
eprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
WARNING:tensorflow:From E:\DL_with_coding\photo2cartoon\utils\face_seg.py:27: The name tf.GraphDef is deprecated. Please use tf.compat.v1.Gra
phDef instead.

**Comment by hao-qiang** [comment]
我们这边win10系统测试可以通过。你似乎已经成功运行了，在images文件夹下没能得到输出结果吗？

**Comment by xiaosuzhang** [comment]
images文件夹没有得到任何结果啊。不知道哪里出现了问题，程序也没有报错

**Comment by WJZYN** [comment]
我这边也是相同的情况，最后lz怎么解决的

**Comment by WJZYN** [comment]
> images文件夹没有得到任何结果啊。不知道哪里出现了问题，程序也没有报错

我这边也是相同的情况，最后lz怎么解决的

**Comment by WJZYN** [comment]
> 我们这边win10系统测试可以通过。你似乎已经成功运行了，在images文件夹下没能得到输出结果吗？
所以作者对这个问题有什么建议吗
if __name__ == '__main__':
    img = cv2.cvtColor(cv2.imread(args.photo_path), cv2.COLOR_BGR2RGB)
    print('yunxing1')
    cartoon = Photo2Cartoon().inference(img)
    print('yunxin2')
    if cartoon is not None:
        cv2.imwrite(args.save_path, cartoon)
运行只能打印yuxing1，yuxing2没有打印

**Comment by hao-qiang** [comment]
> > 我们这边win10系统测试可以通过。你似乎已经成功运行了，在images文件夹下没能得到输出结果吗？
> > 所以作者对这个问题有什么建议吗
> > if **name** == '**main**':
> > img = cv2.cvtColor(cv2.imread(args.photo_path), cv2.COLOR_BGR2RGB)
> > print('yunxing1')
> > cartoon = Photo2Cartoon().inference(img)
> > print('yunxin2')
> > if cartoon is not None:
> > cv2.imwrite(args.save_path, cartoon)
> > 运行只能打印yuxing1，yuxing2没有打印

测试过程有三步：人脸检测及关键点检测、人像分割、卡通化。你可以先定位问题出现在哪一步。

**Comment by WJZYN** [comment]
> 测试过程有三步：人脸检测及关键点检测、人像分割、卡通化。你可以先定位问题出现在哪一

lz您好 测试发现 在人像切割模块face_seg.FaceSeg 函数def _restore_from_pb(self) 中的raph_def.ParseFromString(f.read())这句话有问题，就是进行到这句话时系统自动结束了，不知道您对这个问题怎么看

**Comment by hao-qiang** [comment]
> lz您好 测试发现 在人像切割模块face_seg.FaceSeg 函数def _restore_from_pb(self) 中的raph_def.ParseFromString(f.read())这句话有问题，就是进行到这句话时系统自动结束了，不知道您对这个问题怎么看

windows上tensorflow1.14可以正常运行，你的tensorflow是什么版本。

**Comment by WJZYN** [comment]
> windows上tensorflow1.14可以正常运行，你的tensorflow是什么版本。

您好，我安装的就是1.14

**Comment by cainiaojy** [comment]
> > 测试过程有三步：人脸检测及关键点检测、人像分割、卡通化。你可以先定位问题出现在哪一
> 
> lz您好 测试发现 在人像切割模块face_seg.FaceSeg 函数def _restore_from_pb(self) 中的raph_def.ParseFromString(f.read())这句话有问题，就是进行到这句话时系统自动结束了，不知道您对这个问题怎么看

我也遇到这样的问题，还没解决，你解决了么？

**Comment by WJZYN** [comment]
> 我也遇到这样的问题，还没解决，你解决了么？

说出来有点丢人，作者有些pb文件放在网盘里面，你要先下载下来放在制定文件夹。。。（捂脸

**Comment by cainiaojy** [comment]
> > 我也遇到这样的问题，还没解决，你解决了么？
> 
> 说出来有点丢人，作者有些pb文件放在网盘里面，你要先下载下来放在制定文件夹。。。（捂脸

头像分割模型：seg_model_384.pb，存放在utils路径下 吗？  我放了，分割出来的mask 还是为空。你是怎么解决的？

**Comment by WJZYN** [comment]
那就不知道了 我是因为没下pb文件才跑不出来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jiangyi <notifications@github.com&gt;
发送时间: 2020年4月30日 17:15
收件人: minivision-ai/photo2cartoon <photo2cartoon@noreply.github.com&gt;
抄送: yinan <852266201@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[minivision-ai/photo2cartoon] 关于test (#5)





   
我也遇到这样的问题，还没解决，你解决了么？
  
说出来有点丢人，作者有些pb文件放在网盘里面，你要先下载下来放在制定文件夹。。。（捂脸
  
头像分割模型：seg_model_384.pb，存放在utils路径下 吗？  我放了，分割出来的mask 还是为空。你是怎么解决的？

**Comment by SnrtIevg** [comment]
这跑出来的结果也太娘了吧

**Comment by hao-qiang** [comment]
> 这跑出来的结果也太娘了吧

开源的模型是基于亚洲女性数据训练的。你可以试试我们的小程序，体验不同性别年龄段的效果。

**Comment by SnrtIevg** [comment]
哈哈， 开玩笑，只是体验了一下之前的训练模型，确实太。。。
小程序也体验了一下， 可惜没有硬汉风

**Comment by hao-qiang** [comment]
哈哈，确实，不同用户对风格的期望各不相同，这也是开发这类产品需要仔细衡量的点。
