### ISSUE TITLE
无响应

### ISSUE THREAD

**Issue by fanyushuai** [minivision-ai/photo2cartoon#65]
你好，一开始我找了100多张图，然后开始训练，内存溢出，然后我改为1张图，但是打印training start ! 之后就没反应了，请问是怎么回事？

**Comment by hao-qiang** [comment]
如果是用GPU训练，显存占用量和batch size有关，和训练数据量无关。可能是显存不足导致的。

**Comment by fanyushuai** [comment]
谢谢
