### ISSUE TITLE
官方的漫画api，偶尔出现不正常

### ISSUE THREAD

**Issue by williamqian** [minivision-ai/photo2cartoon#66]
按量付费的，充值了，生成的图片偶尔没有漫画效果，打客服电话直接被挂，微信小助手也没人回，这个服务早点倒闭算了。

**Comment by williamqian** [comment]
原图：
![image](https://user-images.githubusercontent.com/19399075/150290557-1f444608-3ccd-4778-8f8f-0fff6503521a.png)
生成的图：
![image](https://user-images.githubusercontent.com/19399075/150290598-63e820c6-6b2b-4bde-bd20-775d6e53bcb0.png)

**Comment by hao-qiang** [comment]
您好，这张图片生成效果不佳主要是过曝引起的，请尽量选用光照条件较好的照片进行测试。
