### ISSUE TITLE
请问一下为什么不直接使用dlib获得人脸landmarks，而使用face_alignment

### ISSUE THREAD

**Issue by Z863058** [minivision-ai/photo2cartoon#7]
Great work!
请问一下为什么不直接使用dlib的shape_predictor_68_face_landmarks.dat获得人脸landmarks，而使用face_alignment？

**Comment by hao-qiang** [comment]
感谢关注。face-alignment预测关键点的精度和鲁棒性均远好于dlib库，精确的关键点预测更有利于将人脸固定在统一的位置，进而降低训练和测试的难度。
