### ISSUE TITLE
Training on input size (386*386) given an error 

### ISSUE THREAD

**Issue by pradyumnjain** [minivision-ai/photo2cartoon#73]
The training works fine for 128 and 256 input sizes but doesn't work when the input image is not in the power of 2. I received the following error when training with 386*386

RuntimeError: The size of tensor a (193) must match the size of tensor b (192) at non-singleton dimension 3

**Comment by hao-qiang** [comment]
Due to several down-sampling layers, the input size should be divisible by 2 many times. Please try 384*384.
