### ISSUE TITLE
请问大家再使用pycharm来为项目搭建环境，pytroch1.4和tersonflow-gpu1.14下载失败

### ISSUE THREAD

**Issue by TheYMing** [minivision-ai/photo2cartoon#8]

**Comment by hao-qiang** [comment]
安装好python库后，在pycharm中选择对应的interpreter即可。

**Comment by TheYMing** [comment]
请问楼主有空可否出一期csdn来讲解一下搭建环境，我和我同学尝试了二天，都还没有成功，谢谢了。

**Comment by TheYMing** [comment]
或者更加仔细的说明一下环境里面的全部依赖，谢谢了。

**Comment by hao-qiang** [comment]
1. 关于环境搭建的教程网上比较多，您可以查找python3.6的tensorflow和pytorch安装教程，初学者的话可以先尝试安装cpu版本的上述库，本项目在cpu环境下也可以运行测试。
2. 项目主要的依赖库有tensorflow、pytorch、face-alignment（依赖dlib）以及numpy、opencv等常用库，测试时提示缺少哪些库补装一下即可。

**Comment by TheYMing** [comment]
好的，谢谢了
